name: GH Action Test Deploy

on: [push]

jobs:
  check-remote-access:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # - name: 📤 Upload files to server
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.REMOTE_HOST_IPV4 }}
      #     username: ${{ secrets.REMOTE_HOST_USER }}
      #     port: ${{ secrets.REMOTE_HOST_PORT }}
      #     key: ${{ secrets.REMOTE_HOST_KEY }}
      #     source: '.'   # pode ajustar, tipo './src'
      #     target: '~/www/gh-action-test'

      - name: ⚡ Run setup commands on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST_IPV4 }}
          username: ${{ secrets.REMOTE_HOST_USER }}
          port: ${{ secrets.REMOTE_HOST_SSH_PORT }}
          key: ${{ secrets.REMOTE_PUBLIC_KEY }}
          script: |
            mkdir -p ~/www/gh-action-test
            # cd ~/www/gh-action-test
            cp ~/apps/* ~/www/gh-action-test
            # cp ~/apps/env/web/.env.sentry-build-plugin ~/www/gh-action-test
            echo 'Github is here!' >> README.md
